// Generated by the dev-only album-type builder — paste over ALBUM_TYPES and
// ACTIVE_ALBUM_TYPE_ID in src/data/albumTypes.ts.
import type { AlbumType } from './albumTypes';

export const ALBUM_TYPES: Record<string, AlbumType> = {
  "2026-fwc": {
    "id": "2026-fwc",
    "name": "Usa Mex Can 26",
    "variants": [
      {
        "id": "na",
        "label": "North America",
        "region": "🇺🇸🇲🇽🇨🇦 NA edition"
      },
      {
        "id": "latam",
        "label": "Latin America",
        "region": "🌎 LATAM edition"
      }
    ],
    "defaultVariant": "latam",
    "sections": [
      {
        "id": "FWC-trophy",
        "code": "FWC",
        "emoji": "🏆",
        "title": "Panini FIFA World Cup 2026",
        "type": "intro",
        "templateId": "fwc-specials",
        "numbers": [
          "00",
          "1",
          "2",
          "3",
          "4"
        ],
        "foils": [
          "00",
          "1",
          "2",
          "3",
          "4"
        ]
      },
      {
        "id": "FWC-world",
        "code": "FWC",
        "emoji": "⚽",
        "title": "Host Countries and Cities",
        "type": "intro",
        "templateId": "fwc-ball-countries",
        "numbers": [
          "5",
          "6",
          "7",
          "8"
        ],
        "foils": [
          "5",
          "6",
          "7",
          "8"
        ]
      },
      {
        "id": "MEX",
        "code": "MEX",
        "emoji": "🇲🇽",
        "title": "Mexico",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "RSA",
        "code": "RSA",
        "emoji": "🇿🇦",
        "title": "South Africa",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "KOR",
        "code": "KOR",
        "emoji": "🇰🇷",
        "title": "South Korea",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "CZE",
        "code": "CZE",
        "emoji": "🇨🇿",
        "title": "Czechia",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "CAN",
        "code": "CAN",
        "emoji": "🇨🇦",
        "title": "Canada",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "BIH",
        "code": "BIH",
        "emoji": "🇧🇦",
        "title": "Bosnia & Herzegovina",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "QAT",
        "code": "QAT",
        "emoji": "🇶🇦",
        "title": "Qatar",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "SUI",
        "code": "SUI",
        "emoji": "🇨🇭",
        "title": "Switzerland",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "BRA",
        "code": "BRA",
        "emoji": "🇧🇷",
        "title": "Brazil",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "MAR",
        "code": "MAR",
        "emoji": "🇲🇦",
        "title": "Morocco",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "HAI",
        "code": "HAI",
        "emoji": "🇭🇹",
        "title": "Haiti",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "SCO",
        "code": "SCO",
        "emoji": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
        "title": "Scotland",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "USA",
        "code": "USA",
        "emoji": "🇺🇸",
        "title": "United States",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "PAR",
        "code": "PAR",
        "emoji": "🇵🇾",
        "title": "Paraguay",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "AUS",
        "code": "AUS",
        "emoji": "🇦🇺",
        "title": "Australia",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "TUR",
        "code": "TUR",
        "emoji": "🇹🇷",
        "title": "Turkey",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "GER",
        "code": "GER",
        "emoji": "🇩🇪",
        "title": "Germany",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "CUW",
        "code": "CUW",
        "emoji": "🇨🇼",
        "title": "Curaçao",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "CIV",
        "code": "CIV",
        "emoji": "🇨🇮",
        "title": "Côte d'Ivoire",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "ECU",
        "code": "ECU",
        "emoji": "🇪🇨",
        "title": "Ecuador",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "NED",
        "code": "NED",
        "emoji": "🇳🇱",
        "title": "Netherlands",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "JPN",
        "code": "JPN",
        "emoji": "🇯🇵",
        "title": "Japan",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "SWE",
        "code": "SWE",
        "emoji": "🇸🇪",
        "title": "Sweden",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "TUN",
        "code": "TUN",
        "emoji": "🇹🇳",
        "title": "Tunisia",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "CC",
        "code": "CC",
        "emoji": "🥤",
        "title": "Coca-Cola",
        "type": "extra",
        "templateId": "cc-latam",
        "optional": true,
        "numbers": [
          "CC1",
          "CC2",
          "CC3",
          "CC4",
          "CC5",
          "CC6",
          "CC7",
          "CC8",
          "CC9",
          "CC10",
          "CC11",
          "CC12",
          "CC13",
          "CC14"
        ],
        "foils": [],
        "numbersByVariant": {
          "na": [
            "CC1",
            "CC2",
            "CC3",
            "CC4",
            "CC5",
            "CC6",
            "CC7",
            "CC8",
            "CC9",
            "CC10",
            "CC11",
            "CC12"
          ]
        }
      },
      {
        "id": "BEL",
        "code": "BEL",
        "emoji": "🇧🇪",
        "title": "Belgium",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "EGY",
        "code": "EGY",
        "emoji": "🇪🇬",
        "title": "Egypt",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "IRN",
        "code": "IRN",
        "emoji": "🇮🇷",
        "title": "Iran",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "NZL",
        "code": "NZL",
        "emoji": "🇳🇿",
        "title": "New Zealand",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "ESP",
        "code": "ESP",
        "emoji": "🇪🇸",
        "title": "Spain",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "CPV",
        "code": "CPV",
        "emoji": "🇨🇻",
        "title": "Cape Verde",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "KSA",
        "code": "KSA",
        "emoji": "🇸🇦",
        "title": "Saudi Arabia",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "URU",
        "code": "URU",
        "emoji": "🇺🇾",
        "title": "Uruguay",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "FRA",
        "code": "FRA",
        "emoji": "🇫🇷",
        "title": "France",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "SEN",
        "code": "SEN",
        "emoji": "🇸🇳",
        "title": "Senegal",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "IRQ",
        "code": "IRQ",
        "emoji": "🇮🇶",
        "title": "Iraq",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "NOR",
        "code": "NOR",
        "emoji": "🇳🇴",
        "title": "Norway",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "ARG",
        "code": "ARG",
        "emoji": "🇦🇷",
        "title": "Argentina",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "ALG",
        "code": "ALG",
        "emoji": "🇩🇿",
        "title": "Algeria",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "AUT",
        "code": "AUT",
        "emoji": "🇦🇹",
        "title": "Austria",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "JOR",
        "code": "JOR",
        "emoji": "🇯🇴",
        "title": "Jordan",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "POR",
        "code": "POR",
        "emoji": "🇵🇹",
        "title": "Portugal",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "COD",
        "code": "COD",
        "emoji": "🇨🇩",
        "title": "DR Congo",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "UZB",
        "code": "UZB",
        "emoji": "🇺🇿",
        "title": "Uzbekistan",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "COL",
        "code": "COL",
        "emoji": "🇨🇴",
        "title": "Colombia",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "ENG",
        "code": "ENG",
        "emoji": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        "title": "England",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "CRO",
        "code": "CRO",
        "emoji": "🇭🇷",
        "title": "Croatia",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "GHA",
        "code": "GHA",
        "emoji": "🇬🇭",
        "title": "Ghana",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "PAN",
        "code": "PAN",
        "emoji": "🇵🇦",
        "title": "Panama",
        "type": "team",
        "templateId": "country-spread",
        "numbers": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "foils": [
          "1"
        ]
      },
      {
        "id": "FWC-scroll",
        "code": "FWC",
        "emoji": "📜",
        "title": "History",
        "type": "intro",
        "templateId": "fwc-history",
        "numbers": [
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19"
        ],
        "foils": [
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19"
        ]
      }
    ],
    "templates": {
      "country-spread": {
        "id": "country-spread",
        "pageAspect": 0.963,
        "stickerWidthPct": 22.75,
        "pages": [
          {
            "slots": [
              {
                "x": 62.875,
                "y": 15.335774999999998,
                "orientation": "portrait"
              },
              {
                "x": 88.625,
                "y": 15.335774999999998,
                "orientation": "portrait"
              },
              {
                "x": 11.375,
                "y": 50.007324999999994,
                "orientation": "portrait"
              },
              {
                "x": 37.125,
                "y": 50.007324999999994,
                "orientation": "portrait"
              },
              {
                "x": 62.875,
                "y": 50.007324999999994,
                "orientation": "portrait"
              },
              {
                "x": 88.625,
                "y": 50.007324999999994,
                "orientation": "portrait"
              },
              {
                "x": 11.375,
                "y": 84.67887499999999,
                "orientation": "portrait"
              },
              {
                "x": 37.125,
                "y": 84.67887499999999,
                "orientation": "portrait"
              },
              {
                "x": 62.875,
                "y": 84.67887499999999,
                "orientation": "portrait"
              },
              {
                "x": 88.625,
                "y": 84.67887499999999,
                "orientation": "portrait"
              }
            ]
          },
          {
            "slots": [
              {
                "x": 11.375,
                "y": 15.335774999999998,
                "orientation": "portrait"
              },
              {
                "x": 37.125,
                "y": 15.335774999999998,
                "orientation": "portrait"
              },
              {
                "x": 75.75,
                "y": 10.954125,
                "orientation": "landscape"
              },
              {
                "x": 11.375,
                "y": 50.007324999999994,
                "orientation": "portrait"
              },
              {
                "x": 37.125,
                "y": 50.007324999999994,
                "orientation": "portrait"
              },
              {
                "x": 62.875,
                "y": 50.007324999999994,
                "orientation": "portrait"
              },
              {
                "x": 88.625,
                "y": 50.007324999999994,
                "orientation": "portrait"
              },
              {
                "x": 37.125,
                "y": 84.67887499999999,
                "orientation": "portrait"
              },
              {
                "x": 62.875,
                "y": 84.67887499999999,
                "orientation": "portrait"
              },
              {
                "x": 88.625,
                "y": 84.67887499999999,
                "orientation": "portrait"
              }
            ]
          }
        ]
      },
      "fwc-specials": {
        "id": "fwc-specials",
        "pageAspect": 0.863,
        "stickerWidthPct": 22.75,
        "pages": [
          {
            "slots": [
              {
                "x": 56.7,
                "y": 16.5,
                "orientation": "landscape"
              }
            ]
          },
          {
            "slots": [
              {
                "x": 83,
                "y": 12.8,
                "orientation": "landscape"
              },
              {
                "x": 82.5,
                "y": 32.5,
                "orientation": "landscape"
              },
              {
                "x": 83,
                "y": 56,
                "orientation": "landscape"
              },
              {
                "x": 86,
                "y": 83,
                "orientation": "portrait"
              }
            ]
          }
        ]
      },
      "fwc-ball-countries": {
        "id": "fwc-ball-countries",
        "pageAspect": 0.963,
        "stickerWidthPct": 22.75,
        "pages": [
          {
            "slots": [
              {
                "x": 45,
                "y": 30,
                "orientation": "portrait"
              },
              {
                "x": 65,
                "y": 75,
                "orientation": "portrait"
              }
            ]
          },
          {
            "slots": [
              {
                "x": 30,
                "y": 20,
                "orientation": "portrait"
              },
              {
                "x": 65,
                "y": 65,
                "orientation": "portrait"
              }
            ]
          }
        ]
      },
      "cc-latam": {
        "id": "cc-latam",
        "pageAspect": 0.963,
        "stickerWidthPct": 19.25,
        "pages": [
          {
            "slots": [
              {
                "x": 20,
                "y": 45,
                "orientation": "portrait"
              },
              {
                "x": 50,
                "y": 40,
                "orientation": "portrait"
              },
              {
                "x": 80,
                "y": 35,
                "orientation": "portrait"
              },
              {
                "x": 20,
                "y": 80,
                "orientation": "portrait"
              },
              {
                "x": 50,
                "y": 75,
                "orientation": "portrait"
              },
              {
                "x": 80,
                "y": 70,
                "orientation": "portrait"
              }
            ]
          },
          {
            "slots": [
              {
                "x": 20,
                "y": 20,
                "orientation": "portrait"
              },
              {
                "x": 50,
                "y": 20,
                "orientation": "portrait"
              },
              {
                "x": 80,
                "y": 25,
                "orientation": "portrait"
              },
              {
                "x": 20,
                "y": 50,
                "orientation": "portrait"
              },
              {
                "x": 50,
                "y": 50,
                "orientation": "portrait"
              },
              {
                "x": 80,
                "y": 55,
                "orientation": "portrait"
              },
              {
                "x": 20,
                "y": 80,
                "orientation": "portrait"
              },
              {
                "x": 50,
                "y": 80,
                "orientation": "portrait"
              }
            ]
          }
        ]
      },
      "fwc-history": {
        "id": "fwc-history",
        "pageAspect": 0.963,
        "stickerWidthPct": 22.75,
        "pages": [
          {
            "slots": [
              {
                "x": 27.5,
                "y": 50,
                "orientation": "landscape",
                "decorative": true
              },
              {
                "x": 72.5,
                "y": 50,
                "orientation": "landscape"
              },
              {
                "x": 27.5,
                "y": 80,
                "orientation": "landscape",
                "decorative": true
              },
              {
                "x": 72.5,
                "y": 80,
                "orientation": "landscape"
              }
            ]
          },
          {
            "slots": [
              {
                "x": 27.5,
                "y": 20,
                "orientation": "landscape"
              },
              {
                "x": 72.5,
                "y": 20,
                "orientation": "landscape",
                "decorative": true
              },
              {
                "x": 27.5,
                "y": 50,
                "orientation": "landscape"
              },
              {
                "x": 72.5,
                "y": 50,
                "orientation": "landscape",
                "decorative": true
              },
              {
                "x": 27.5,
                "y": 80,
                "orientation": "landscape",
                "decorative": true
              },
              {
                "x": 72.5,
                "y": 80,
                "orientation": "landscape"
              }
            ]
          },
          {
            "slots": [
              {
                "x": 27.5,
                "y": 20,
                "orientation": "landscape",
                "decorative": true
              },
              {
                "x": 72.5,
                "y": 20,
                "orientation": "landscape",
                "decorative": true
              },
              {
                "x": 27.5,
                "y": 50,
                "orientation": "landscape"
              },
              {
                "x": 72.5,
                "y": 80,
                "orientation": "landscape",
                "decorative": true
              },
              {
                "x": 27.5,
                "y": 80,
                "orientation": "landscape"
              },
              {
                "x": 72.5,
                "y": 50,
                "orientation": "landscape",
                "decorative": true
              }
            ]
          },
          {
            "slots": [
              {
                "x": 27.5,
                "y": 20,
                "orientation": "landscape"
              },
              {
                "x": 72.5,
                "y": 20,
                "orientation": "landscape"
              },
              {
                "x": 27.5,
                "y": 80,
                "orientation": "landscape",
                "decorative": true
              },
              {
                "x": 72.5,
                "y": 50,
                "orientation": "landscape"
              },
              {
                "x": 27.5,
                "y": 50,
                "orientation": "landscape",
                "decorative": true
              },
              {
                "x": 72.5,
                "y": 80,
                "orientation": "landscape"
              }
            ]
          }
        ]
      }
    }
  }
};

export const ACTIVE_ALBUM_TYPE_ID = "2026-fwc";
